sonar.projectKey=PPL-BRIN-2025_pantautular-fe-2025
sonar.organization=ppl-brin-2025

sonar.projectName=pantautular-fe-2025
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=__tests__

# IGNORE test folder berikut:
sonar.test.exclusions= \

# Test inclusions tetap umum saja
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

# encoding
sonar.sourceEncoding=UTF-8

# Coverage
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info
